version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: HeroesPostgres
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
